### ISSUE TITLE
Option to set "transport" in the config

### ISSUE THREAD

**Issue by deepinder19** [nameko/nameko-sentry#19]
```transport``` has been hardcoded to ```EventletHTTPTransport``` but it would be nice if we can have the option to set it in the config file.

**Comment by deepinder19** [comment]
The issue is that I am able to send exceptions to sentry using ```ThreadedHTTPTransport``` but not using ```EventletHTTPTransport```.

**Comment by mattbennett** [comment]
@deepinder19 why doesn't `EventletHTTPTransport` work for you?

Nameko relies on Eventlet, so nameko-sentry using eventlet threads should be fine...

**Comment by deepinder19** [comment]
The issue was related to ssl certificates error on my local machine. Apparently ssl certificates needs to be installed manually if using Python 3.6 on Mac. And sentry was failing silently because of this error.
